// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAWb4yQVa9qdoHbgSELM1Pv6oH6LNY_fg',
    appId: '1:790305346030:android:6f59beb8ee940e6656feff',
    messagingSenderId: '790305346030',
    projectId: 'geonotes-da3a3',
    storageBucket: 'geonotes-da3a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABSmeZsvRD1P-GTQEzN1I0bpNZ9OSsR6Y',
    appId: '1:790305346030:ios:2207dd1ac6f22ab756feff',
    messagingSenderId: '790305346030',
    projectId: 'geonotes-da3a3',
    storageBucket: 'geonotes-da3a3.appspot.com',
    androidClientId: '790305346030-01vcurj5vbdfuaon10ef4d9mohlb26vc.apps.googleusercontent.com',
    iosClientId: '790305346030-pe3hhrhk39flo3kqj2rigfomjkti8k1p.apps.googleusercontent.com',
    iosBundleId: 'io.rylero.geonotes',
  );
}
